name: Create Document Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version, e.g. X.Y.Z:'
        required: true
        type: string
      prerelease:
        description: 'Tag as a pre-release?'
        required: false
        type: boolean
        default: true
      draft:
        description: 'Create release as a draft?'
        required: false
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # Pull the latest RISC-V Docs container image
    # https://github.com/riscv/riscv-docs-base-container-image
    # https://hub.docker.com/r/riscvintl/riscv-docs-base-container-image
    - name: Pull Container
      run: |
        docker pull riscvintl/riscv-docs-base-container-image:latest
    - name: Pull Container
      run: |
        docker pull riscvintl/riscv-docs-base-container-image:latest
    - name: Set Commit Date and Git Version
      run: |
        echo "COMMITDATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
        echo "GITVERSION=v${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - name: Build Files
      run: |
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            -e GITVERSION \
            -e COMMITDATE \
            riscvintl/riscv-docs-base-container-image:latest \
            /bin/sh -c 'make'
  
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/*.pdf
        tag_name: v${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        draft: ${{ github.event.inputs.draft }}
        prerelease: ${{ github.event.inputs.prerelease }}
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
